name: Deploy build to Hugging Face

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Prepare deploy folder
        run: |
          mkdir deploy
          cp -r build/* deploy/
          cp Dockerfile deploy/

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          cd deploy
          git init
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "Deploy build folder"
          git branch -M main
          git remote add origin https://$HF_TOKEN@huggingface.co/spaces/conc1se/winwin_evidence.git
          git push --force origin main
