name: Deploy build to Hugging Face

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          lfs: true  # 여기서도 Git LFS 활성화

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Prepare deploy folder
        run: |
          mkdir deploy
          cp -r build/* deploy/
          cp Dockerfile deploy/

      - name: Push to Hugging Face Space with Git LFS
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          cd deploy
          git init
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"

          git lfs install
          git lfs track "*.wasm"
          git lfs track "*.woff2"
          git lfs track "*.woff"
          git lfs track "*.ttf"
          git add .gitattributes

          git add .
          git commit -m "Deploy build folder with Git LFS"
          git branch -M main

          git remote add origin https://oauth2:$HF_TOKEN@huggingface.co/spaces/conc1se/winwin_evidence.git
          git push --force origin main
